import { useEffect, useRef, useState } from 'react'
import { profile, projects } from './portfolio'

function Art({ project }) {
  return <div className={`project-art ${project.visual}`} aria-hidden="true">{project.visual === 'orbit' ? <><i /><i /><span>{project.shortTitle}</span><small>{project.category}</small></> : project.visual === 'forma' ? <><div className="product-window"><small>● ● ●</small><strong>{project.shortTitle}<br />{project.title === 'ExpenseTracker' ? 'Built for offline.' : 'A little progress, daily.'}</strong><div className="bars"><i /><i /><i /><i /></div></div><span>{project.shortTitle}</span></> : <><div className="contours">{Array.from({ length: 12 }, (_, i) => <i key={i} style={{ '--i': i }} />)}</div><span>{project.shortTitle}</span><small>{project.category}</small></>}</div>
}

export default function App() {
  const [menu, setMenu] = useState(false)
  const [paused, setPaused] = useState(false)
  const [selected, setSelected] = useState(null)
  const [copied, setCopied] = useState(false)
  const scene = useRef(null)
  const dialog = useRef(null)
  const projectTrigger = useRef(null)
  useEffect(() => { if (selected) dialog.current.showModal() }, [selected])
  function move(event) {
    const rect = event.currentTarget.getBoundingClientRect()
    scene.current.style.setProperty('--rx', `${-(event.clientY - rect.top - rect.height / 2) / 22}deg`)
    scene.current.style.setProperty('--ry', `${(event.clientX - rect.left - rect.width / 2) / 22}deg`)
  }
  function reset() { scene.current.style.setProperty('--rx', '0deg'); scene.current.style.setProperty('--ry', '0deg') }
  async function copy() { try { await navigator.clipboard.writeText(profile.email); setCopied(true) } catch { setCopied(false) } }
  return <><a className="skip" href="#main">Skip to content</a><div className="shell">
    <header><a className="brand" href="#home"><b>{profile.initials}</b><span>{profile.name}<small>{profile.role}</small></span></a><button className="menu-button" aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? 'Close -' : 'Menu +'}</button><nav id="navigation" className={menu ? 'open' : ''} aria-label="Main navigation"><a href="#work" onClick={() => setMenu(false)}>Work</a><a href="#about" onClick={() => setMenu(false)}>About</a><a className="nav-contact" href="#contact" onClick={() => setMenu(false)}>Let’s talk ↗</a></nav></header>
    <main id="main"><section className="hero" id="home"><div><p className="eyebrow"><i className="status" /> NUZRAN NAZEER / SOFTWARE DEVELOPER</p><h1>Complex problems.<br />Thoughtful code.<br /><em>Real impact.</em></h1><p className="hero-description">I build secure web applications and offline-first mobile experiences with on-device AI. Currently seeking a software engineering internship.</p><a className="button" href="#work">Explore my work <span>↗</span></a><a className="text-link" href="#about">A little about me ↓</a></div>
    <div ref={scene} className={`scene ${paused ? 'paused' : ''}`} onPointerMove={move} onPointerLeave={reset}><div className="grid" /><div className="glow" /><div className="object-position"><div className="tilt"><div className="sculpture" aria-hidden="true">{Array.from({ length: 18 }, (_, i) => <i key={i} style={{ '--i': i }} />)}</div></div></div><span className="code-label">&lt; / &gt;<small>CODE MEETS CREATIVITY</small></span><span className="scene-diamond" aria-hidden="true" /><div className="scene-bottom"><span>MOVE YOUR CURSOR TO EXPLORE</span><button aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? 'Resume motion ↻' : 'Pause motion Ⅱ'}</button></div></div>
    <div className="hero-footer"><span>DESIGNED TO EXPLORE. BUILT TO CONNECT.</span><a href="#work">SCROLL TO DISCOVER ↓</a></div></section>
    <div className="ticker" aria-hidden="true"><span>THOUGHTFUL DESIGN</span><i className="ticker-divider" /><span>FULL-STACK DEVELOPMENT</span><i className="ticker-divider" /><span>OFFLINE-FIRST MOBILE</span></div>
    <section id="work" className="section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, brought <em>to life.</em></h2></div><p>Web, mobile, and the systems behind them.<br /><small>Explore my contributions and technical decisions.</small></p></div><div className="projects">{projects.map((project, i) => <button className="project-card" key={project.title} onClick={event => { projectTrigger.current = event.currentTarget; setSelected(project) }} aria-label={`View ${project.title} details`}><Art project={project} /><div className="project-info"><div><p>{project.category} / 0{i + 1}</p><h3>{project.title}</h3></div><span>↗</span></div><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></button>)}</div></section>
    <section id="about" className="section about"><div className="about-art" aria-hidden="true"><div className="orbital-mark"><i /><i /><i /></div><span>A LITTLE CURIOSITY<br />GOES A LONG WAY.</span></div><div><p className="eyebrow">02 / THE PERSON BEHIND THE PIXELS</p><h2>Curious by nature.<br /><em>Driven to build.</em></h2><p>{profile.about}</p><p>{profile.approach}</p><h3>My toolkit</h3><div className="skills">{profile.skills.map(skill => <span key={skill}>{skill}</span>)}</div></div></section>
    <section className="section education" aria-labelledby="education-heading"><p className="eyebrow">LEARNING / FOUNDATIONS</p><h2 id="education-heading">Always <em>learning.</em></h2><div className="education-grid">{profile.education.map(item => <article key={item.title}><p>{item.period}</p><h3>{item.title}</h3><p>{item.institution}</p></article>)}</div><p className="certifications">Certifications: BCS HEQ Diploma and Certificate in IT; Trainee Full Stack Developer (UOM CODL); Foundations of Cybersecurity, Play It Safe: Manage Security Risks, and Connect and Protect: Networks and Network Security (Google); Introduction to DevOps and Introduction to Cloud Computing (IBM).</p><a className="text-link cv-link" href="/nuzran-nazeer-cv.pdf" target="_blank" rel="noreferrer">Read my CV ↗</a></section>
    <section id="contact" className="section contact"><p className="eyebrow">03 / NEXT CHAPTER</p><h2>Have something<br />in mind? <em>Let’s talk.</em></h2><p>Great things start with a simple hello.</p>{profile.email ? <div className="contact-actions"><a className="button" href={`mailto:${profile.email}`}>Say hello ↗</a><button className="text-link" onClick={copy}>{copied ? 'Email copied ✓' : 'Copy email'}</button><span className="sr-only" role="status">{copied ? 'Email copied to clipboard' : ''}</span></div> : <p className="contact-placeholder">Your contact link goes here.<br /><small>Add your email in src/portfolio.js to enable contact.</small></p>}<div className="contact-orbit" aria-hidden="true"><i /><i /></div></section></main>
    <footer><a href="#home">{profile.name} </a><span>© {new Date().getFullYear()} · Built with curiosity.</span><div>{profile.github && <a href={profile.github} target="_blank" rel="noreferrer">GitHub ↗</a>}{profile.linkedin && <a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a>}<a href="#home">Back to top ↑</a></div></footer></div>
    <dialog ref={dialog} onClose={() => { setSelected(null); projectTrigger.current?.focus() }} onClick={event => { if (event.target === event.currentTarget) dialog.current.close() }} aria-labelledby="project-title">{selected && <div><button className="close" onClick={() => dialog.current.close()} aria-label="Close project">×</button><Art project={selected} /><p className="eyebrow">{selected.role}{selected.period && ` / ${selected.period}`}</p><h2 id="project-title">{selected.title}</h2><p>{selected.description}</p><h3>My contribution</h3><ul className="contributions">{selected.highlights.map(item => <li key={item}>{item}</li>)}</ul>{selected.metrics && <div className="metrics">{selected.metrics.map(metric => <span key={metric}>{metric}</span>)}</div>}<h3>Technologies</h3><div className="skills">{selected.stack.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-links">{selected.url && <a className="button" href={selected.url} target="_blank" rel="noreferrer">View live project ↗</a>}{selected.repo && <a href={selected.repo} target="_blank" rel="noreferrer">Source code ↗</a>}</div></div>}</dialog></>
}
